### ISSUE TITLE
Request for Grades, Weeks 14-15

### ISSUE THREAD

**Issue by HannahDelaney** [HannahDelaney/ecommerce-pattern-library#12]
@thomasjbradley, I have those two surprise pages ready!

Surprise Page One:
I think my patterns handled this decently. I had to add some pre-existing classes to make sure that  there was a visible hierarchy. Something that I noticed (that I knew would possibly be my downfall here) was that the way my headings cascade was more out of convenience of certain styles I knew I wanted to use, rather than based on a hierarchy of them displaying content in a more typical order like this. For example, my `h3` / `h5`, and `h4` / `h6` tags, look the same as each other. Despite this though, I think I managed to use my other patterns to make the page look good! The other issue was that I did not have the foresight to style my table elements individually. This was only a problem at my smaller screens sizes, although I should definitely have had those pieces prepared.

Surprise Page Two:
I think I was fairly prepared for all of this content! I created a subscribe banner a while ago even though it wasn't in my original UX design because I felt like the site needed one, so that was ready. I had also thought early on that it might be fun to have icons prepared for when items were new or on sale, so those were ready to go too. I was happy to get to use them! The only piece I was not as on top of was the alert bar banner, but I used my shop page divider to achieve the effect I needed.

**Comment by thomasjbradley** [comment]
They look great!
