### ISSUE TITLE
Request for marks for content from Weeks 10-12

### ISSUE THREAD

**Issue by HannahDelaney** [HannahDelaney/ecommerce-pattern-library#2]
Hello @thomasjbradley,

I've got a few things I need to collect marks for.

Start with 2 quizzes:
![image](https://user-images.githubusercontent.com/43122774/77782553-d5bd1780-702d-11ea-954b-24380a6c8389.png)
![image](https://user-images.githubusercontent.com/43122774/77782492-c0e08400-702d-11ea-85da-821830db0798.png)

Completed lessons and activities:
- Jekyll Generators
- Homepage Template
- Finalizing Pattern docs
- Product List Page Template

Thanks so much!
Hannah

**Comment by thomasjbradley** [comment]
:shipit:

**Comment by HannahDelaney** [comment]
:shipit: 👍
