### ISSUE TITLE
Categorizing and limiting

### ISSUE THREAD

**Issue by HannahDelaney** [HannahDelaney/ecommerce-pattern-library#3]
Hey again @thomasjbradley,

I'm trying to finished an extra pattern I realized I needed for my product page. It is a small list of "related" products to feature below the main product on a given page.

I am trying to use the `limit:2` with Jeykll to have a max of 2 items appear, from the category that the product on the page is also a part of. I am not sure if I need to specify them separately with 3 different if statements, or if it matters that there are 6 in the honey and body categories but only 3 in the candle category.

Are you able to have a look at the related.html file in my pattern/sections and suggest how I might achieve this?

Thanks so much.

**Comment by thomasjbradley** [comment]
You could try something like this:

```html
{% assign related_products=site.shop|where:"category","body" %}
{% for product in related_products limit:2 %}
```

Then get rid of the the `{% if %}` statement inside the loop.

This way we create a new array of products that only has the body category—and we loop through those, limiting to 2.

**Comment by HannahDelaney** [comment]
This worked well! I switched out "body" for page.category, so it will only show products from the correct category.

Now to just figure out how to randomize...

Thanks, Thomas 😄

**Comment by thomasjbradley** [comment]
Jekyll doesn’t randomize very well because it builds the page only once. So you could get a randomization per-page-save but not per-page-load in the browser.

**Comment by HannahDelaney** [comment]
Yes, I have been trying to look into it online and it wasn't looking good. Although a per page save might still not be a terrible option, or the first 2 alphabetical products will be the consistent best-sellers! I can keep looking into ways to do that though.

I suppose my only other slight fix for that would be a way to not have it possible to show the same product in the related list that is currently being displayed (like listing bubble bath as related to bubble bath). Is something like that possible?

**Comment by thomasjbradley** [comment]
Oh—I found a possible solution. Instead of `limit:2` try `sample:2` — It’ll pick 2 random things from the list instead of the first two.

**Comment by HannahDelaney** [comment]
Hm, it kept in category but displayed all six of the options instead of two. Is there a way to use the sample, but still limit the sample to two?

**Comment by thomasjbradley** [comment]
Oh, I used it wrong, try this:

```
{% for product in related_products|sample:2 %}
```

**Notice the `|` in there.**

**Comment by HannahDelaney** [comment]
Shoot, no luck with that either, it still displays all six.

**Comment by thomasjbradley** [comment]
Maybe move it up here:

```
{% assign related_products=site.shop|where:"category","body"|sample:2 %}
```

**Comment by HannahDelaney** [comment]
Hooray! That worked!

A bunch of them randomly still have the first related product as the same one listed for that product page, but not all of them are like that. Weird sampling is weird.

Thanks so much Thomas! 
Have a great weekend, hope you get some rest.

**Comment by thomasjbradley** [comment]
Yeah, random is... random.
