### ISSUE TITLE
Request for Grades Week 13-14

### ISSUE THREAD

**Issue by HannahDelaney** [HannahDelaney/ecommerce-pattern-library#5]
Hey @thomasjbradley,

Finished my checkout form page! :shipit: Also adjusted some other small pieces across the site (my product page banners reflect the individual products now, and I made the bottom banner for that page match my original design rather than use a subscribe banner. Caught wind I might need that elsewhere..).

I'm having a weird capitalization conundrum with some of my cards, but I'll write a separate issue for those if I can't figure it out.

Happy holiday weekend!

**Comment by thomasjbradley** [comment]
🔥
