### ISSUE TITLE
Includes not loading

### ISSUE THREAD

**Issue by HannahDelaney** [HannahDelaney/ecommerce-pattern-library#6]
Hey @thomasjbradley,

I'm having a weird issue with my pattern library not updating to the localhost. I realized I had an error with my card arrangement, which are on all my banners, because any page that has more than one banner is going to have more than one h1, which obviously isn't great.

I tried to create an if statement to load an alternate `<p>` instead of the h1 for pages where this will be necessary, but the new `h1-alt` include I created is not loading. I'm refreshing my library, and the page, and not seeing the new include appear.

I was working within the dark card pattern, and product layout html file, for reference.

**Comment by thomasjbradley** [comment]
I think it’s because `h1-alt` is missing in this line:
https://github.com/HannahDelaney/ecommerce-pattern-library/blob/master/_patterns/banners/banner-dark-card.html#L4

**Comment by HannahDelaney** [comment]
Yes, that was it. I knew it was going to be something silly and small.

Thank you!
