### ISSUE TITLE
Google Page Speed Analysis

### ISSUE THREAD

**Issue by MissMadore** [HannahDelaney/ecommerce-pattern-library#7]
@thomasjbradley

This page performs really well according to Google Page Speed! Apparently there is some sort of font-display css that we can take advantage of to ensure text is user-visible while webfonts are loading.

<img width="759" alt="Screen Shot 2020-04-17 at 2 17 45 PM" src="https://user-images.githubusercontent.com/43224886/79601085-3a601500-80b6-11ea-8bff-ee722b6eefed.png">
<img width="756" alt="Screen Shot 2020-04-17 at 2 15 33 PM" src="https://user-images.githubusercontent.com/43224886/79601089-3c29d880-80b6-11ea-9ae7-530c098043ce.png">

**Comment by HannahDelaney** [comment]
That's a neat feature, I've added some things to swap the fonts.

Thanks!
