### ISSUE TITLE
Mobile Opera Issues

### ISSUE THREAD

**Issue by MacKenzieRose** [HannahDelaney/ecommerce-pattern-library#9]
Hi @HannahDelaney @thomasjbradley

The only issue I'm really seeing is with the cards with landscape view on:
![IMG_0621](https://user-images.githubusercontent.com/19557909/79602171-0259d180-80b8-11ea-9659-75f8001dfb7b.png)
![IMG_0618](https://user-images.githubusercontent.com/19557909/79602173-02f26800-80b8-11ea-8896-2cbfdee7d473.png)

Other than that, maybe consider the line breaks here:
![IMG_0620](https://user-images.githubusercontent.com/19557909/79602373-5b296a00-80b8-11ea-8526-7ace80093d02.png)

But mostly, I just wanted to tell you how much I love this:

![IMG_0622](https://user-images.githubusercontent.com/19557909/79602415-6d0b0d00-80b8-11ea-8b94-70cdbedcf759.png)

Nicely done :)
MacKenzie

**Comment by HannahDelaney** [comment]
Whoa! Wacky. Yeah I definitely did not consider it rotating on a phone, my phone browser was not doing that.

I'll see if I can address this! Thanks!
